# Generated by Django 4.0.2 on 2022-03-01 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='cover_page',
            field=models.ImageField(blank=True, null=True, upload_to='video/PortadaVideo'),
        ),
    ]
