# Generated by Django 3.0.2 on 2022-03-05 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0004_auto_20220305_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('estadoCivil', models.CharField(blank=True, choices=[('0', 'Soltero'), ('1', 'Casado/a'), ('2', 'Separado/a'), ('3', 'Divorciado/a'), ('4', 'Viudo/a')], max_length=1, null=True)),
                ('escolaridad', models.CharField(blank=True, choices=[('0', 'Primaria'), ('1', 'Secundaria'), ('2', 'Preparatoria'), ('3', 'Tecnica'), ('4', 'Profesional'), ('3', 'Maestria'), ('6', 'Doctorado')], max_length=1, null=True)),
                ('phoneNumber', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('estado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.Municipio')),
            ],
            options={
                'verbose_name': 'Padrino',
                'verbose_name_plural': 'Padrinos',
            },
            bases=('users.user',),
        ),
    ]
