# Generated by Django 3.0.2 on 2022-03-05 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('padrino', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('padrino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='padrino.Padrino')),
                ('escuela', models.CharField(max_length=150)),
                ('kardex', models.FileField(upload_to='kardex')),
            ],
            options={
                'verbose_name': 'Niño',
                'verbose_name_plural': 'Niños',
            },
            bases=('padrino.padrino',),
        ),
    ]
