# Generated by Django 3.0.2 on 2022-03-05 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220305_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Niño',
            fields=[
                ('padrino_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.Padrino')),
                ('escuela', models.CharField(max_length=150)),
                ('kardex', models.FileField(null=True, upload_to='kardex')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.padrino',),
        ),
        migrations.AddField(
            model_name='padrino',
            name='escolaridad',
            field=models.CharField(blank=True, choices=[('0', 'Primaria'), ('1', 'Secundaria'), ('2', 'Preparatoria'), ('3', 'Tecnica'), ('4', 'Profesional'), ('3', 'Maestria'), ('6', 'Doctorado')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='padrino',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('0', 'Soltero'), ('1', 'Casado/a'), ('2', 'Separado/a'), ('3', 'Divorciado/a'), ('4', 'Viudo/a')], max_length=1, null=True),
        ),
    ]
