# Generated by Django 4.0.2 on 2022-03-02 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_municipality_user_state_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='state',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='municipality',
            new_name='municipio',
        ),
    ]
