# Generated by Django 3.0.2 on 2022-03-05 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0003_auto_20220305_1319'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrino',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='padrino',
            name='municipio',
        ),
        migrations.RemoveField(
            model_name='padrino',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='Niño',
        ),
        migrations.DeleteModel(
            name='Padrino',
        ),
    ]
