# Generated by Django 4.0.2 on 2022-03-02 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_state_user_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='user',
            name='municipio',
        ),
    ]
