# Generated by Django 4.0.2 on 2022-03-02 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0005_remove_user_date_birth_remove_user_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('date_birth', models.DateField(blank=True, null=True, verbose_name='Fecha de nacimiento')),
                ('estado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='location.estado')),
                ('municipio', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='estado', chained_model_field='estado', null=True, on_delete=django.db.models.deletion.CASCADE, to='location.municipio')),
            ],
            options={
                'abstract': False,
            },
            bases=('users.user',),
        ),
    ]
