# Generated by Django 4.0.2 on 2022-03-03 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_padrino'),
    ]

    operations = [
        migrations.AddField(
            model_name='padrino',
            name='tel',
            field=models.PositiveIntegerField(null=True, verbose_name='Numero de telefono'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ocupation',
            field=models.CharField(blank=True, choices=[('0', 'Administrador'), ('1', 'Padre'), ('2', 'Niño'), ('3', 'Padrino')], max_length=1),
        ),
    ]
