# Generated by Django 4.0.2 on 2022-03-03 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_padrino_tel_alter_user_ocupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='padrino',
            name='tel',
            field=models.IntegerField(null=True, verbose_name='Numero de telefono'),
        ),
    ]
