# Generated by Django 4.0.2 on 2022-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_padrino_tel_padrino_phonenumber_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='padrino',
            name='secondPhoneNumber',
        ),
        migrations.AlterField(
            model_name='padrino',
            name='phoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
